FROM serversideup/php:8.4-fpm-nginx AS php_base

USER root
RUN install-php-extensions intl

WORKDIR /var/www/html

# Copy composer files only
COPY --chown=www-data:www-data ./src/composer.json ./

# Install production PHP deps
RUN composer install --no-dev --optimize-autoloader --no-scripts --no-interaction


# -----------------------------------------------------
# NODE BUILD STAGE
# -----------------------------------------------------
FROM node:20 AS node_build

WORKDIR /app

# Copy only package files to use build cache
COPY ./src/package.json ./
COPY ./src/package-lock.json ./

RUN npm ci

# Copy full source
COPY ./src .

RUN npm run build


# -----------------------------------------------------
# FINAL RUNTIME IMAGE
# No node, no node_modules, only PHP + built assets
# -----------------------------------------------------
FROM php_base AS final

WORKDIR /var/www/html

# Copy full Laravel code
COPY --chown=www-data:www-data ./src .

# Copy built assets from node stage
COPY --from=node_build /app/public/build ./public/build

# Fix perms
RUN chmod -R 755 storage bootstrap/cache

USER www-data
